### ISSUE TITLE
`predict` should work on `DataFrameRow`

### ISSUE THREAD

**Issue by adienes** [alan-turing-institute/MLJ.jl#1004]
**Describe the bug**

Let `X` be a DataFrame and `mach` be a fitted machine.

`predict(mach, X[1:1, :])` works as expected, but `predict(mach, X[1, :])` errors.

Version 0.19.1

**Comment by ablaom** [comment]
Thanks @adienes for reporting. I wouldn't characterise this as a bug but expected behaviour. You do not specify the model you are using but models that accept tables for training generally expect tables for predicting. A `DataFrameRow` is not a table, so not supported. 

```julia
julia> df = DataFrame((x=rand(4), y=rand(4)));

julia> Tables.istable(df[1:1, :])
true

julia> Tables.istable(df[1, :])
false
```

More generally, predicting on a single observation not wrapped as a collection is not supported. 

Does that make sense?

**Comment by adienes** [comment]
I see, that does make sense thank you for the explanation.

I suppose a follow up question would be if it would be reasonble for `predict` to work also on `Tables.AbstractRow` s?

**Comment by ablaom** [comment]
Well, for uniformity of interface, we would require predictions on "single observations" for all manner of containers, not just tables. Without a strong use-case, I don't see adding this feature being a priority, and it has not been raised previously. 

Perhaps this a suggestion you could make at this design proposal re a future API: https://discourse.julialang.org/t/ann-learnapi-jl-proposal-for-a-basement-level-machine-learning-api/93048/20 .

**Comment by adienes** [comment]
Gotcha. I certainly think it's important to be able to do predictions on single observations, but I suppose in these cases the `AbstractRow` can usually be wrapped up into a proper table without much issue
