### ISSUE TITLE
misclassification_rate StackOverflow error

### ISSUE THREAD

**Issue by pazzo83** [alan-turing-institute/MLJ.jl#133]
Hi, the two method definitions of `misclassification_rate` could potentially yield a call that ends with a Stack Overflow error (due to the same method getting called in an infinite loop).

You have these two definitions:
```
misclassification_rate(yhat::AbstractVector{<:CategoricalElement},
                       y::AbstractVector) = mean(y .!= yhat)
misclassification_rate(yhat, y::AbstractVector) = 
    misclassification_rate(mode.(yhat), y)
```
If you call the method with `yhat` being a vector of floats, for example, it will call that same method an infinite number of times (thus leading to the stack overflow).  Because `yhat` is never converted to the type of vector expected by the first method definition, you get stuck.

**Comment by ablaom** [comment]
Good point. I thought about explicitly requiring the second yhat to have elements the isdistribution trait but that complicates the interface and we plan to replace this code with integration with LossFunctions anyway. 

 If you make yhat a vector of floats you should be getting an error anyway (admittedly and more informative one) because that is not an appropriate type for classification.  Has this caused actual difficulties, or just confusion?
