### ISSUE TITLE
Scitypes for images

### ISSUE THREAD

**Issue by ablaom** [alan-turing-institute/MLJ.jl#134]
Couple of options here. 

1. **Make a composite of existing types** We define scitpye of an `AbstractArray{T}`  to be `AbstractArray{scitype{T}}` and have aliases like `GreyImage = AbstractArray{Continuous,2}`, `ColorImage = AbstractImage{Continuous,3}`.

2. **Add new types to hierarchy** as in `ColorImage <: Image <: Found` and declare `scitype(AbstractArray{<:AbstractFloat}, 3) = ColorImage` and so forth (or replace with some julia standard image custom format).

I kinda like first option but just want start a discussion.

@fkiraly

**Comment by datnamer** [comment]
What about interfacing with the images ecosystem type tree?

**Comment by ablaom** [comment]
Thanks for that.

I think I would regard the image custom types as "machine types" as distinct with "scientific types". Scientific types are used as values of a bunch of MLJ trait functions: `scitype` (saying what scientific type a regular "machine" type has) `input_scitype_union` (what scitypes are are allowed for a given model's input), `target_scitype_union` (what scitypes are allowed for the target of a supervised model), and so forth.  

We accommodate the custom image types by a simple declaration in case 2 (as in `scitytype(TheirCustomTypeForColorImages) = ColorImage`.  

To see if Case 1 can work, I do have to look a bit closer at those types. If the custom images types are are `AbstractArray{<:AbstractFloat}` then that probably works too.

**Comment by fkiraly** [comment]
Very interesting question (I wonder what brought it on, is it flux?).

Just to note this, very similar but somewhat simpler questions emerge when you talk about series, sequences, or bags instead of images - in my internal "scitype hierarchy" these are "simpler" complex types, simply singe an image has 2D (or 3D if you count colour scheme) internal structure and all kinds of meta-data. So if we have leeway to prioritize, I would advocate "simpler things first".

Regarding scitype of an image: I think it is naturally, at the same time, composite (meta-data and the following), higher-order (pixel representation), and dependent (size etc).

I'd make it a decorated abstract array, and its own type. Not sure whether that maps on 1 or 2, I don't think so since both try to equate images with arrays (albeit in different directions).

I don't like either of 1,2, to be honest, because it makes any array of 2D or 3D format automatically an "image". I think whether a data structure of that shape should be considered an image is up to the user/experimenter, no? Similar to whether a real vector should be interpreted categorical ar not, it is a matter of data specification than of data representation.

Important subsidiary questions arise when you start thinking about *annotated* images, such as images with landmarks, images with ROIs, and images with a segmentation. If you talk about the types and scitypes of images, you also need to think carefully about what is the (sci)type of a collection of segments that points at one specific image.

**Comment by fkiraly** [comment]
Just to briefly summarize yesterday's verbal discussion with @davidbp and @ablaom : 

I thought (and we agreed - or the other way round?) that there is worth in an explicit declaration of whether an array should be considered an image, or not. This is since the classes of methods that are likely to work for images, or to try first of images, are substantially different to classes of methods that one would apply to or find promising for generic arrays of the same format.

As @davidbp remarked, the API of images.jl forces the user to make that explicit declaration by converting array elements to a colors.jl type.

Multiple machine types, not necessarily partial-order dominated by one type, can be "greyscale" etc, that rules out option 1.

Therefore, wouldn't the best option be sth like
`scitype(AbstractArray{ColorTypes.RGB{Float32}}, 2) = ColorImage`
and
`scitype(AbstractArray{Color{N0f8}, 2) = ColorImage`
etc?

Note that use of "child of common ancestor type" as suggested in option 2 is not possible since there is no single "antecessor color type" in the color.jl type hierarchy:
https://github.com/JuliaGraphics/ColorTypes.jl
`Color` is an antecessor of `Gray` and RBG types, whereas `AbstractRGB` is not an antecessor of HSV or YIQ which are also colour types. There does not exist a common antecessor of colour types which is not antecessor of grayscale types, I believe - but even if there were, there could still be other representations of colour images than in-menory colors.jl arrays.

**Comment by ablaom** [comment]
[ScientificTypes.jl](https://github.com/alan-turing-institute/ScientificTypes.jl) adopts something close to the suggestion of @fkiraly and MLJ 0.4.0 implements the convention there.
