### ISSUE TITLE
scitype

### ISSUE THREAD

**Issue by fkiraly** [alan-turing-institute/MLJ.jl#155]
This is in reflection upon #81, #119 and #134 and perhaps a couple others, after I think I've understood better the lookup and typing issues.

I think it's a general design problem that there are multiple methods that return scitypes, this includes, but is perhaps not limited to `scitype`, `scitype_union`, `scitypes`, `target_scitype_union`, `input_scitype_union` and probably a few others that @ablaom has hidden well.

Here's a suggestion: why not uniformize this, and just have a *single* scityping function `scitype`, which behaves exactly like `typeof`, just with scientific types.

The scitype of a learner can be a (possibly parametric) struct type with fields `input`, `target` that can be union types.
The scitype of a data frame can simply be its type schema plus size - also a struct type, with parametric member types. One of these could be the "schema", which could be a `NamedTuple` type where the names are variable names, the other could be the value type "size" (number of rows).

So: why define separate scitype functions that in reality look up fields of the "real" scitype if we can use Julia dispatch?

**Comment by fkiraly** [comment]
@datnamer, in response to #81 discussion: with the above, we don't need to rewrite typing in the Julia language, since we can write our own version of `typeof` - i.e., `scitype`- right? So, no need to bother @JeffBezanson (yet).

**Comment by datnamer** [comment]
That makes sense to me

**Comment by ablaom** [comment]
@fkiraly Thanks for your feedback. I don't see a rationale for changing the status quo. Let me explain the raison d`etre for these methods.

The reason we have a `scitype` and a separate `scitypes` for tables is same reason we distinguish between the machine type of a table and its schema, namely that they are different:

```julia
julia> using MLJ, Tables

julia> X = load_reduced_ames().X;    # a DataFrame

julia> typeof(X)
DataFrame

julia> Tables.schema(X)
Tables.Schema:
 :OverallQual   Float64                  
 :GrLivArea     Float64                  
 :Neighborhood  CategoricalString{UInt32}
 :x1stFlrSF     Float64                  
 :TotalBsmtSF   Float64                  
 :BsmtFinSF1    Float64                  
 :LotArea       Float64                  
 :GarageCars    Float64                  
 :MSSubClass    CategoricalString{UInt32}
 :GarageArea    Float64                  
 :YearRemodAdd  Float64                  
 :YearBuilt     Float64                  
```

... and in complete analogy, we have:

```julia
julia> scitype(X)
Unknown

julia> scitypes(X)
(OverallQual = Continuous,
 GrLivArea = Continuous,
 Neighborhood = Multiclass{25},
 x1stFlrSF = Continuous,
 TotalBsmtSF = Continuous,
 BsmtFinSF1 = Continuous,
 LotArea = Continuous,
 GarageCars = Continuous,
 MSSubClass = Multiclass{15},
 GarageArea = Continuous,
 YearRemodAdd = Continuous,
 YearBuilt = Continuous,)
```

In other words, if we apply your simplification argument to machine types, then we would redefine `typeof` for tables to return the schema, which would be absurd. So I am just trying to be consistent here. 

The method `scitype_union` is just a convenience function for the MLJ core developer, because he gets tired of typing `reduce((a,b)->Union{a,b}, (scitype(el) for el in A))` all the time.

In my opinion, to combine the values of the model trait functions `target_scitype_union`  and `input_scitype_union` into a new stuct and call that the `scitype` of the model is an abuse of the method's original intention. In my view, anything that returns a `scitype` that is not `Unknown` is, by convention, something you can put into a table that some learning algorithm knows how to interpret (Continuous, Image, and so forth). Incidentally, this may one day include things for which `is_table` returns `true`, ie we might have tables within tables, which is another argument for keeping the distinction `scitype`/`scitypes`.

Is this clear, or am I missing something?

There are no other hidden scitype methods. A free cigar for routing them all out!

For your convenience I am copying some related doc strings:

---
    scitype(x)

Return the scientific type that an object `x` can represent, when
appearing as an element of a table or vector used as input or target
in fitting MLJ models.

    julia> scitype(4.5)
    Continous

    julia> scitype("book")
    Unknown

    julia> using CategoricalArrays
    julia> v = categorical([:m, :f, :f])
    julia> scitype(v[1])
    Multiclass{2}

Note that `scitype` "commutes" with the formation of tuples or arrays,
as these examples illustrate:

```julia
scitype((42, float(π), "Julia"))
```

```julia 
Tuple{Count,Continuous,Unknown}
```

```julia
scitype(rand(7,3))
```

```julia
AbstractArray{Continuous,2}
```

For getting the union of the scitypes of all elements of an iterable,
use `scitype_union`.

---
    scitype_union(A)

Return the type union, over all elements `x` generated by the iterable
`A`, of `scitype(x)`.

---
    scitypes(X)

Returns a named tuple keyed on the column names of the table `X` with
values the corresponding scitype unions over a column's entries.

---

**Comment by fkiraly** [comment]
Thanks for the clarification (smoking an imaginary free cigar).

The documentation you posted is exactly what I looked up, so if you will my opinion is not caused by not having seen it.

Regarding the point you raise about `DataFrame`: I think the status quo that you base your counterargument on is actually an inconsistency in `typeof`, or how the type of a data frame is defined.

Arrays are types that are first-order and parametric:
`Array{Union{ImaginaryCigar, Int64}, 2}`
and so on. That is, the type of an array "remembers" what entry types it can have.

If the same logic were to be extended to `DataFrames`, the very type of a data frame should remember what types it has in its columns, that is, its schema. 

The analogue of calling `Tables.schema` on a data frame to see its content types, for arrays, is calling some method `ohArray.whatisthytype` on an array (that unlike it is now in Julia) is not a parametric first-order type but just a plain (atomic/zeroth-order/non-parametric) type `Array`.

That is, my argument is, in a clean typing language, perhaps there should not have been a `Tables.schema` in the first place, but the list of column types should perhaps be a member type of the data frame type which is a struct.

Now I'm sure DataFrames.jl will have thought carefully about whether to do that, because of pre-compilation etc and how `typeof` plays into this. But some of these considerations are perhaps nothing one would have to worry about with `scitype`?

Does it make more sense now where I'm coming from?
(blowing an imaginary smoke ring while imagining the imaginary increase of risk for small-cell lung cancer)

**Comment by fkiraly** [comment]
Perhaps one thing to add: for a data container, it perhaps seems "obvious" what the scitype should be: return the same structure or type, replace types/elements by scitypes.

However, I think it's very much worth thinking about whether "the scitype of a learner" makes any sense. Given that it has "input scitypes" and "output scitypes", would the scitype not be sensibly made up of these? E.g., the type of ordinary regression being "I'm a supervised learner which can take continuous inputs and will produce a continuous output"?

**Comment by ablaom** [comment]
@fkiraly Okay, I see your point more clearly now. So you would define the `scitype` operation to "commute with" all containerisations (not just tuples) as in `scitype(Array{Float63, 3}) = Array{Continuous, 3}` and include all tables that support it (`DataFrames` not being a case-in-point). Then, in the special case that a container is itself a candidate for a new scitype (eg an array type for images) we overload `scitype` to overide this behaviour?

This is a good idea but it may be overcommitting ourselves, for this suggests implementing this behaviour for every single container type, no? 

In fact (I didn't mention this before)  in trying to implement this behaviour simultaneously for all subtypes of `AbstractArray`, we already have in MLJBase, `MLJBase.scitype(A::B) where {T,N,B<:AbstractArray{T,N}} = AbstractArray{scitype(first(A)),N}` which gives `scitype(Array{Float63, 3}) = AbstractArray{Continous, 3}` (not quite what we might want). I think you get a sense of what is involved, though. Is this really worth it?

In regard to using `scitype` for models. I am very reluctant to *replace* the traits `input_union_scitype` and `target_union_scitype` (which are only for model implementers really) because this would break a lot of code.  We could, against my better judgement, override `scitype` on models so that it returns these trait in  a named tuple or something. The general user already has access to these traits by going `info(model)`. Is your request because you think it benefits the developer, or because you think it's better for the general user?

**Comment by fkiraly** [comment]
@ablaom, I don't think we should do anything against your better judgment since I do trust it...

But I think what you describe is in line with the idea.

To comment on reasons, my suggestion is because:
(1) I think in the medium term, it would be better to devs and users to locate all the `scitype` lookups with a single interface point, since (1.a) it avoids having to remember all the various scitype related functions in favour of a single one which should return the requested information in "obvious" structure, and (1.b) it seems more intuitive to me to consider all objects with a "scientific type"
(2) I think it may enable us to leverage elegant solutions to some of the issues raised in #81, #119 and #134 , which otherwise would lead to definition of more scitypey methods

Regarding "methods with different functions should have different names", I agree, but I don't think this applies as a problem to the suggestion, since scityping isn't a different function(ality), it's just applied to different kinds of objects.
And isn't providing the same or similar kind of cuntion to differen kind of objects a very Julian thing to do - as in "dispatch"?

**Comment by fkiraly** [comment]
Maybe an addendum regarding the overloading point: I think automatic overloading should be avoided.
In the case of images, there should be a place where the user should explicitly declare whether they want to consider an array as image or not. It's not the type system that should infer this, subject to sensible defaults of course.
Where to put this kind of declaration is an interesting secondary question i.m.o.: at the level of dataset container construction (collection of images in dataframe/iterable)? at the level of the sample ("image")? or, by direct declaration using scitype?

**Comment by ablaom** [comment]
Franz, another problem is that the scitype of an object cannot be deduced from its machine type, even  in the most basic examples: https://github.com/JuliaData/CategoricalArrays.jl/issues/184#issue-413204945

**Comment by fkiraly** [comment]
>another problem is that the scitype of an object cannot be deduced from its machine type

That's sort-of clear to me, which is why scitype should optimally not be a function of machine type, but a property of the object (which could be queried to a method similar to `typeof`).

**Comment by fkiraly** [comment]
It would appear we've slipped back into the scitype discussion in #176 , adding the reference here for good measure. Also, I just want to point out that @ablaom started it.

**Comment by ablaom** [comment]
[ScientificTypes.jl](https://github.com/alan-turing-institute/ScientificTypes.jl) represents a pretty concerted effort to resolve the issues raised in the initial comment in this thread, and I'm going to close this now.
