### ISSUE TITLE
Scitype & Missing

### ISSUE THREAD

**Issue by vollmersj** [alan-turing-institute/MLJ.jl#173]
**Describe the bug**
The scitype DataFrame column with float and missing is just missing

**To Reproduce**
```
df=DataFrame(x=vcat([missing,1.0],ones(10)),y=vcat([missing,1.0],ones(10)),z=vcat([missing,1.0],ones(10)))
scitype(df[:y])
```

**Comment by fkiraly** [comment]
That's because it's looking at the first element, it would appear to me, definition being:

```MLJBase.scitype(A::B) where {T,N,B<:AbstractArray{T,N}} = AbstractArray{scitype(first(A)),N}```

**Comment by fkiraly** [comment]
The fix is reasonably easy by replacing `scitype(first(A))` with the scitype of `typeof(df[:y]).parameters[1]`, but the question is what should be standard behaviour:
(1) recursing through type parameters and replacing atomic (zeroth order) types with their scitypes
(2) going down just one level and replacing that by scitypes, e.g., if it's a data frame containing images = greyscale arrays

I think it should be (2), but I also think we need to specify this carefully before implementing another hack.

**Comment by ablaom** [comment]
Yes, this is a bug but perhaps what you wanted to do is `scitype_union(df[:y])`?

```julia
julia> scitype_union(df[:y])
Union{Missing, Continuous}
```

**Comment by fkiraly** [comment]
Ouch, shouldn't the scitype of a vector be a vector of scitypes, actually?

**Comment by ablaom** [comment]
Yes, it will be something like that before we are done.

**Comment by ablaom** [comment]
Under MLJ 0.3.0:

```julia
julia> df=DataFrame(x=vcat([missing,1.0], ones(10)),
       y=vcat([missing,1.0],ones(10)),
       z=vcat([missing,1.0],ones(10)))
12×3 DataFrame
│ Row │ x        │ y        │ z        │
│     │ Float64⍰ │ Float64⍰ │ Float64⍰ │
├─────┼──────────┼──────────┼──────────┤
│ 1   │ missing  │ missing  │ missing  │
│ 2   │ 1.0      │ 1.0      │ 1.0      │
│ 3   │ 1.0      │ 1.0      │ 1.0      │
│ 4   │ 1.0      │ 1.0      │ 1.0      │
│ 5   │ 1.0      │ 1.0      │ 1.0      │
│ 6   │ 1.0      │ 1.0      │ 1.0      │
│ 7   │ 1.0      │ 1.0      │ 1.0      │
│ 8   │ 1.0      │ 1.0      │ 1.0      │
│ 9   │ 1.0      │ 1.0      │ 1.0      │
│ 10  │ 1.0      │ 1.0      │ 1.0      │
│ 11  │ 1.0      │ 1.0      │ 1.0      │
│ 12  │ 1.0      │ 1.0      │ 1.0      │

julia> scitype(df[:y])
AbstractArray{Union{Missing, Continuous},1}
```
