### ISSUE TITLE
Data science and ML ontologies in MLJ

### ISSUE THREAD

**Issue by juliohm** [alan-turing-institute/MLJ.jl#189]
I am opening this issue just to share a website that may be useful to the MLJ org. It would be nice to understand the ontologies that are being developed, and to contribute to this development within the MLJ project: www.datascienceontology.org

Could you please share your thoughts regarding existing ontologies and how MLJ is planning to incorporate these efforts?

**Comment by juliohm** [comment]
Also relevant to this thread:

- https://www.w3.org/community/ml-schema/
- http://htmlpreview.github.io/?https://github.com/ML-Schema/documentation/blob/gh-pages/ML%20Schema.html

**Comment by vollmersj** [comment]
Dear @juliohm,

thank you very much - thanks for the pointers. We are still following this up very closely. As prelimanry response we are working on an integration to OpenML (second link of yours) which for we are in conversation with Joaquin Vanschoren and @darenasc will attend the openml sprint in the fall. Do you have much experience working with these ontologies yourself?

**Comment by juliohm** [comment]
Thank you @vollmersj for sharing. I am not the appropriate person to discuss ontologies, but I am happy to know that this is in MLJers radar. Should we close the issue?

**Comment by fkiraly** [comment]
@juliohm - this is very much related to the scitypes discussion #155 etc!

I think a scitype of a method/algorithm should be a full ontological description.
The tags, traits, etc we are currently using are ontological properties.

I'd be very much in favour of mlj doing that properly, eventually - clean interface design is very much related to definition of clean ontologies.

Regarding the stuff you linked, I think our design is better since we have categories (encoded through types) and hierarchical and referential ontologies (encoded through sub-types and references).

**Comment by juliohm** [comment]
Thank you all for the comments. I will close the issue since the links are already in your radar.
