### ISSUE TITLE
use MLMetrics to remove redundant code

### ISSUE THREAD

**Issue by ayush1999** [alan-turing-institute/MLJ.jl#20]
Looks like there's a plan to use MLMetrices for basic utilities (as given in poster and discussed on the call). Essentially, most of the code in https://github.com/alan-turing-institute/MLJ.jl/blob/master/src/metrics.jl is the re-implementation of MLMatrices functions. Would be good to maintain uniformity and use the already implemented and tested functions.
@ablaom Need your go-ahead on this before making a PR.

**Comment by ablaom** [comment]
My understanding from the meeting and earlier discussions with @sjvollmer is that we should *not* use MLMetrics at this point, because it is apparently not yet sufficiently stable. For now, I just dumped some metrics from Koala.jl to get us up and running without a dependency. There are tests for these metrics in the current code. I would not object to renaming these to conform with MLMetrics names.

**Comment by ablaom** [comment]
After having another look at MLMetrics, I don't think it is ready to serve our purposes, especially with regard to evaluating probabilistic learners. I am closing this issue for now.
