### ISSUE TITLE
Make CSV an explicit (non-optional) dependency again

### ISSUE THREAD

**Issue by ablaom** [alan-turing-institute/MLJ.jl#224]
To make `load_iris()` and so forth work again without `import CSV`?

**Comment by ablaom** [comment]
I've got a better idea. Leave CSV as optional dependency but turn the `load_iris` command into a macro that automatically imports CSV. This breaks the syntax, but this is going to break anyway when tasks change.

**Comment by jpsamaroo** [comment]
Making CSV a hard dependency just so the user can load a pre-shipped dataset or two definitely seems wrong to me, since then users pay the constant price of loading CSV at startup (which is non-negligible last I checked).

Either making the dataset loaders into macros, or waiting on Julia to start prompting the user if they want to add a package when they try to load one which isn't installed (sorry, can't find the issue/PR for this), seems best to me.

**Comment by ablaom** [comment]
Agreed. Macros coming soon.

**Comment by ablaom** [comment]
Resolved by #39, now merged onto master.
