### ISSUE TITLE
@load is too slow

### ISSUE THREAD

**Issue by tlienart** [alan-turing-institute/MLJ.jl#280]
I believe we discussed this already but it's probably a good idea we keep track of this issue.

The first call to `@load RidgeRegressor pkg="ScikitLearn"` will understandably be a bit slow because it loads `ScikitLearn` in the enfironment. However I don't see why if it's re-evaluated it should still be slow?

**Comment by juliohm** [comment]
I would like to take this opportunity to also reiterate a design decision that I think is sub-optimal. This `@load` macro could be moved to, or at least exported in `MLJBase.jl` so that other projects integrated with MLJ.jl are able load models without having to add MLJ.lj explicitly in Project.toml files. I am releasing a notebook soon that illustrates this issue.

**Comment by ablaom** [comment]
Had a quick look. To check if code is already loaded, there is a call to `localmodels()`

```julia
julia> @time localmodels()
  1.513531 seconds (3.66 M allocations: 212.595 MiB, 1.47% gc time)
8-element Array{NamedTuple,1}:
 (name = ConstantClassifier, package_name = MLJModels, ... )         
 (name = ConstantRegressor, package_name = MLJModels, ... )          
 (name = FeatureSelector, package_name = MLJModels, ... )            
 (name = OneHotEncoder, package_name = MLJModels, ... )              
 (name = Standardizer, package_name = MLJModels, ... )               
 (name = StaticTransformer, package_name = MLJModels, ... )          
 (name = UnivariateBoxCoxTransformer, package_name = MLJModels, ... )
 (name = UnivariateStandardizer, package_name = MLJModels, ... )     
```

This does seem a bit slow. But I have not investigated further. 

The work-around is to instantiate the model directly. There is no need to call @load every time:

`model = RidgeRegressor()`

instead of 

`model = @load RidgeRegressor`

@juliohm 

@load is in now in MLJModels because that is where the model registry lives. Separating the two would certainly be suboptimal. The reason we don't have the registry in MLJBase is:

(i) MLJBase is intended to provide code necessary for developers to implement the MLJ model API for their model, and should provide nothing else. This design decision was based on advice from @MikeInnes with further consensus articulated in https://github.com/alan-turing-institute/MLJBase.jl/issues/19. I also think it is a good idea.  

(ii) If the registry were to be moved to MLJBase, then every time we update the registry we would need to release a new MLJBase version. Currently we tag a new MLJModels version, which is very convenient, as this is where many model interfaces are added (almost all of them at present).

If you need @load (and therefore the registry) and you don't want to import MLJ, I suggest you import MLJModels, a repo with few dependencies beyond `MLJBase` and only a small amount of non-optional code (which might become optional later anyhow).

**Comment by juliohm** [comment]
Thank you @ablaom. I wonder if just exporting the name `@load` in MLJBase.jl would solve the issue? The implementation of the macro would still live in `MLJModels.jl`. With this simple change, users of projects that are integrated with the MLJ.jl stack (e.g. GeoStats.jl, other projects which depend on `MLJBase.jl`) could load models directly. Currently I am forcing users to load the entire MLJ.jl stack just to gain access to the `@load` macro.

The following change should be enough for all use cases:

```julia
module MLJBase
...
export @load
...
end

module MLJModels
...
import MLJBase: @load
...
end
```

**Comment by ablaom** [comment]
This seems like a bad idea. 

Are we to add to the namespace of MLJBase every time some package in the  ecosystem adds functionality? By the same argument, I would add the methods to implement resampling strategies, tuning strategies, etc etc . It seems to me that an advantage of modularisation is precisely to avoid such complications. 

If you want the functionality provided by MLJModels, I suggest you make it part of your stack. As I argue above, if MLJBase is already in your stack the cost is minimal (and likely to go down, rather than up, if some or all of the "built-in models" are migrated to lazily loaded packages).

**Comment by juliohm** [comment]
> Are we to add to the namespace of MLJBase every time some package in the ecosystem adds functionality? By the same argument, I would add the methods to implement resampling strategies, tuning strategies, etc etc . It seems to me that an advantage of modularisation is precisely to avoid such complications.

I think resampling strategies, tuning strategies are all good candidates for a "*Base" package or a separate package that is not MLJ.jl. So if these methods and strategies are not accessible in lower packages in the stack, then the answer is yes. They could go down to a more "*Base" namespace for other projects to reuse them.

> If you want the functionality provided by MLJModels, I suggest you make it part of your stack. As I argue above, if MLJBase is already in your stack the cost is minimal (and likely to go down, rather than up, if some or all of the "built-in models" are migrated to lazily loaded packages).

My point is that MLJModels.jl is not something conceptual. I don't want to depend on a repository that is a collection of other repositories with learning models. The concept of "loading a model", however, is something that is part of *any* ML workflow, and that is why it deserves a space in MLJBase.jl IMO. I don't need to know which model is to be loaded. I only need to know that there is a function called "@load" that is used to load models into memory, and that this function can be used in projects that are integrated with MLJ.jl stack.

**Comment by ablaom** [comment]
A note that the original issue in this thread has been addressed:

https://github.com/alan-turing-institute/MLJModels.jl/pull/113

**Comment by ablaom** [comment]
Yes, @juliohm, you're right. It does make sense to put things the bare tuning interface into MLJBase, for the same reason it makes sense to have the bare model interface there. 

I guess I'm not seeing `@load` as part of an interface, that is, something to be extended? It's just a function, which I imagined to be attached to model loading and nothing else. Are you wanting to repurpose it somehow?

**Comment by juliohm** [comment]
At the moment, my only use of the `@load` macro is the use it was designed for. No intention to repurpose it.

**Comment by ablaom** [comment]
Then I don't understand how you can avoid depending on MLJModels. 

> My point is that MLJModels.jl is not something conceptual. I don't want to depend on a repository that is a collection of other repositories with learning models. 

I am happy, however, for your reasons to remain a mystery to me, and will add the @load stub in the next MLJBase minor release.
