### ISSUE TITLE
FAQ for Julia Meetup 22.10.2019

### ISSUE THREAD

**Issue by vollmersj** [alan-turing-institute/MLJ.jl#286]
Place to collect questions

**Comment by oxinabox** [comment]
Using symbols like `prediction_type==: probabilistic`,
Rather than singleton types,
Feels bad:
 - easy to make typos
 - can't dispatch on (need to wrap in `Val`)
 - rely on constant propagation for optimisation (rather than specialisation)
 - harder to extend later (e.g. by adding parameters, or working with unions)

**Comment by oxinabox** [comment]
Everyone should start using Scientific Types

It is just something we should all centre around 



There is a version of this logic in:
 - LowRankModel.jl
 - MLLabelUtils.jl
 - StatsModels
 - VegaLite.jl

and probably more


I really want to convege all the versions of this logic into one thing.
that covers at fine-grained level what qualia the types have (and gives overwriting).
Then things that consume it like VegaLite can map those fine grained categories to there own like Continous->Quant, Binary->Nominal, Categorical->Nominal, etc
