### ISSUE TITLE
Serialization

### ISSUE THREAD

**Issue by tlienart** [alan-turing-institute/MLJ.jl#292]
A few people have tried or asked about how to save work in MLJ, thinks like trained machines, or trained networks, or what indices things were trained on etc.

Naively trying to use `JLD2.@save "file.jld2" trained_machine` seems to work but then can't be loaded properly.
Another user tried to save to BSON file and when loading that crashed Julia. Some of this may be related to what modules are available in your environment at  the time of loading. 

I think discussing and documenting the workflow to save ongoing work would be useful; possibly this has been discussed in the past but I wasn't able to find the discussion or a relevant pointer in the doc (?).

**Comment by metanoid** [comment]
I'm the user who tried BSON, but I now think the issue resulted from my use of `XGBoostClassifier` as the model for the `machine` I was trying to save.  My theory is that `BSON` saved the _pointer_ to the `XGBoost` model, rather than the model itself, and so on reload it was pointing to a non-existent object, thus causing the crash.  I think this because switching from `BSON` to `JLD2` (and making no other changes) leads to the following error message:  `cannot write a pointer to JLD file`.  

Nonetheless I am still interested in finding a way to save `MLJ` machines and reload them for later use.

**Comment by metanoid** [comment]
FWIW, saving a `machine{OneHotEncoder}` with BSON and JLD2 both seem to work correctly.

**Comment by ablaom** [comment]
Existing issue:

https://github.com/alan-turing-institute/MLJ.jl/issues/138
