### ISSUE TITLE
[suggestions] Unroll the network in `@from_network`

### ISSUE THREAD

**Issue by tlienart** [alan-turing-institute/MLJ.jl#311]
Unless I misunderstand how it works, the `@from_network` works like this:

```
@from_network CompositeModel(comp1=comp1, comp2=comp2) <= yhat
```

where yhat is the final node of a network previously defined. 

Why can't `comp1`, `comp2` etc, be inferred from `yhat`? i.e. could we have a syntax

```
CompositeModel = @from_network yhat
```

I'd find this a bit more natural; possibly to help with this, nodes in the network could be given names 

```julia
Xs = source(X)
ys = source(y, kind=:target)

stand = machine(Standardizer(), Xs)
W = transform(stand, Xs; name=:std)

box = machine(UnivariateBoxCoxTransformer(), ys)
z = transform(box, ys; name=:box)

ridge = machine(RidgeRegressor(lambda=0.1), W, z)
ẑ = predict(ridge, W; name=:ridge)

ŷ = inverse_transform(box, ẑ; name=:out)

CompositeModel = @from_network ŷ
```

As an aside, I don't like the syntax

```julia
instance = @... Name ... 
```

as it creates two things which is confusing, it creates a model constructor and it creates an instance; in the tutorials  as a result I never create the instance. Maybe that something like

```
ModelName = @pipeline(....) <: Probabilistic
Network = @from_network final_node <: Probabilistic 
```

makes more sense (?)

**Comment by tlienart** [comment]
an amusing (?) side note is

```
@from_network CompositeModel1() <= yhat
```

stack overflows

**Comment by ablaom** [comment]
@tlienart Thanks for these suggestions.

For the benefit of others, here is the doctoring describing the status quo:  

---
    @from_network(NewCompositeModel(fld1=model1, fld2=model2, ...) <= N
    @from_network(NewCompositeModel(fld1=model1, fld2=model2, ...) <= N is_probabilistic=false
    
Create a new stand-alone model type called `NewCompositeModel`, using
a learning network as a blueprint. Here `N` refers to the terminal
node of the learning network (from which final predictions or
transformations are fetched). 

*Important.* If the learning network is supervised (has a source with
`kind=:target`) and makes probabilistic predictions, then one must
declare `is_probabilistic=true`. In the deterministic case the keyword
argument can be omitted.

The model type `NewCompositeModel` is equipped with fields named
`:fld1`, `:fld2`, ..., which correspond to component models `model1`,
`model2`, ...,  appearing in the network (which must therefore be elements of
`models(N)`).  Deep copies of the specified component models are used
as default values in an automatically generated keyword constructor
for `NewCompositeModel`.

### Return value
A new `NewCompositeModel` instance, with default field values.

---

So, "fld1" tells the macro a field name you want in the new model type created, while "model1" is essentially a pointer to the place in the network that the corresponding value is to be put *and* what  the default value should be.  Both are essential ingredients for the macro to have.

Important to keep in mind that we are not identifying nodes or machines here, just models: two machines could point to the same model instance (as in a homogenous ensemble) and two nodes could point to the same machine (as is the case for target transformations). 

In the `names=...` syntax being suggested names are being given to *nodes* not models. However, from each node name we can deduce a corresponding model. One problem is this: A specific model might appear in more than one node, while the node labelling will account for only one of these locations. 

Perhaps @tlienart may have a suggestion in the same spirit that circumvents this problem?

I should say an advantage that of the status quo that I like is that there is no new syntax to learn to build the learning network, except "wrap data in source nodes" and you can drop the intermediate calls to fit because you just fit the whole network.

I must say I have never been completely happy with the syntax of the macro calls themselves and appreciate the suggestions. I do like "<: Probablistic" and don't like the existing "<= yhat" much. And I would acknowledge your confusion around the type/instance thing. Perhaps the syntax should look more like a regular struct definition with some decorations, and, well, if you want an instance, you should just define it. 

What do you think?

**Comment by tlienart** [comment]
Hmm ok; I think the status quo is fine but I'd like to see whether something more compact can also be supported in line with arrow syntax. Doing something like:

```julia
z = Target() |> UnivariateBoxCoxTransformer()
r = (Input(), z) |> RidgeRegressor()
yhat = r |> inverse_transform(z)

CompositeModel = @model yhat

m = machine(CompositeModel(), X, y)
fit!(m, rows=train)
```

Further,

```julia
S = Input() |> Standardizer() 
P = S |> PCA()

CompositeModel2 = @model E
CompositeModel3 = CompositeModel2() |> CompositeModel()
```

And now access is done via the name of nodes

```julia
CompositeModel3.P.maxoutdim = 3
CompositeModel3.r.lambda = 0.3
```

Of course if the two models have a node with the same name that would be ambiguous but this could be automatically detected and a numbering could be added  in  such case

```julia
CompositeModel.nodename_1.hp = ...
CompositeModel.nodename_2.hp = ...
```

So I guess there are several ideas here:

1. Have `Input()` and `Target()` create anonymous source nodes so  that a network is not directly  tied to data
2. Allow unrolling with inferred model names
3. Resolve eventual clashes by numbering nodes if there are several of them

Of course there may  be reasons for not  doing all this, these are just ideas. It's just noteworthy that I find the arrow syntax very convenient but once I have to  write a `@from_network` it kills the whole  compactness etc which is not so nice

**Comment by ablaom** [comment]
Short note:

> Have Input() and Target() create anonymous source nodes so that a network is not directly tied to data

This is already possible: `source()` is aliased to `source(nothing)`, which is allowed, and `source(; name=name)` is aliased to `source(nothing, name=name)`. There is no requirement that source nodes wrap actual data, unless one wants to call `fit` on a node in the network.

**Comment by ablaom** [comment]
Closing in favour of https://github.com/alan-turing-institute/MLJBase.jl/issues/267
