### ISSUE TITLE
Show less when showing models

### ISSUE THREAD

**Issue by tlienart** [alan-turing-institute/MLJ.jl#351]
This is more of an aesthetic request (coming from MLJTutorials). Can we have the show discard the first `MLJModels.SubPackage_.` ? so that:

```
MLJModels.DecisionTree_.DecisionTreeClassifier(pruning_purity = 1.0,
                                               max_depth = -1,
                                               min_samples_leaf = 1,
                                               min_samples_split = 2,
                                               min_purity_increase = 0.0,
                                               n_subfeatures = 0,
                                               display_depth = 5,
                                               post_prune = false,
                                               merge_purity_threshold = 0.9,
                                               pdf_smoothing = 0.05,) @ 1…40
```

becomes

```
DecisionTreeClassifier(pruning_purity = 1.0,
                       max_depth = -1,
                       min_samples_leaf = 1,
                       min_samples_split = 2,
                       min_purity_increase = 0.0,
                       n_subfeatures = 0,
                       display_depth = 5,
                       post_prune = false,
                       merge_purity_threshold = 0.9,
                       pdf_smoothing = 0.05,) @ 1…40
```

arguably no less informative. Same for  `MLJ.ProbabilisticTunedModel` etc. Additionally  the current  behaviour  is a bit inconsistent since we  have  `Machine{ProbabilisticTunedModel}` 

Or at least could we have a setting where this can be toggled like `color_off` ?

I haven't looked at which  show produces  this so I don't  know which one should be edited but glad to produce a PR once I know what causes this

#### Additional request

To reduce horizontal overflow, could we agree to place the first kwarg on the first line after? so that it's  not aligned with  the first bracket? i.e.:

```
DecisionTreeClassifier(
    pruning_purity = 1.0,
    max_depth = -1,
    min_samples_leaf = 1,
    min_samples_split = 2,
    min_purity_increase = 0.0,
    n_subfeatures = 0,
    display_depth = 5,
    post_prune = false,
    merge_purity_threshold = 0.9,
    pdf_smoothing = 0.05,) @ 1…40
```

this would greatly help the display of nested models...

**Comment by juliohm** [comment]
Also is it possible to remove the trailing @1..40 that shows at the end of the model? That is a very nice feature request, thanks.

**Comment by tlienart** [comment]
@juliohm I think the trailing `@...` is actually informative in some cases (if there is possible ambiguities between several machines with the same models) but it (and the FR above) could/should be toggle-able I think (as the use of colours is currently toggleable with `MLJ.color_off()`)

**Comment by ablaom** [comment]
@tlienart Happy for you to play around with this. You will want to check that any changes still make sense for models with *nested* hyperparameters (ie, need extra layer of indendatation for each layer of nesting). Best  I can tell, the relevant method is `pretty(stream, object::M, current_depth, depth, n)` on line 151 of MLJBase/src/show.jl,  which is a recursive function. It seems that the line 

```julia
  prefix = string(coretype(typeof(object)))
```

is not always working as expected, so we just need some string manipulations to strip off leading junk, instead of using  `coretype`. 

FYI

- There is a trait `show_as_constructed` which says if an MLJType object should be shown as constructed, which is true for all subtypes of `Model` but fallback to false. That's why machines are not displayed like this. I think most of the field values of machines are not going to be of interest to general user, so they are not being displayed by default. 

- The default depth of nesting in objects that "show_as_constructed" is controlled by global constant DEFAULT_SHOW_DEPTH, currently 2 I think. 

- Developers can get a complete "dump" of an MLJType instance (eg, a machine) by typing `@more` after the object at the REPL. 

- `Nodes` in learning networks have their own show method, as you will have observed. This could be improved but is not a high priority,  in my opinion. 

- You can change the trailing `1...34` into a meaningful handle with the use of the `@constant` macro. I found this more of a pain after a while, so did not document  it:

```julia
julia> using MLJ
julia> @constant X = source()
Source{:input} @ X

julia> @constant y = source(kind=:target)
Source{:target} @ y

julia> @constant pca = @load PCA
PCA(maxoutdim = nothing,
    method = :auto,
    pratio = 0.99,
    mean = nothing,) @ pca

julia> @constant tree = @load DecisionTreeRegressor
DecisionTreeRegressor(pruning_purity_threshold = 0.0,
                      max_depth = -1,
                      min_samples_leaf = 5,
                      min_samples_split = 2,
                      min_purity_increase = 0.0,
                      n_subfeatures = 0,
                      post_prune = false,) @ tree

julia> @constant pca_mach = machine(pca, X)
NodalMachine @ pca_mach = machine(PCA @ pca, X)

julia> @constant W = transform(pca_mach, X)
Node @ W = transform(pca_mach, X)

julia> @constant tree_mach = machine(tree, W, y)
NodalMachine @ tree_mach = machine(DecisionTreeRegressor @ tree, W, y)

julia> @constant yhat = predict(tree_mach, W)
Node @ yhat = predict(tree_mach, transform(pca_mach, X))
```

**Comment by ablaom** [comment]
@tlienart 's suggestion will appear in the next minor release.
