### ISSUE TITLE
Improved docs for the data interface between MLJ and the world

### ISSUE THREAD

**Issue by baggepinnen** [alan-turing-institute/MLJ.jl#379]
Continuation from slack discussion. 

My background is much more matrices and vectors whereas the docs highlight a lot of dataframes features. Maybe a dedicated input output section of the docs would be a good idea, where the input section has a dataframes subsection and one kind of raw numerical arrays section.

My first experience with MLJ required a lot of time to figure out I had to call table on my matrix. It's in the docs, but I somehow missed it for almost an hour. 

As input, the user might come with something like a dataframe or just a numerical matrix. As output from MLJ, the user might want some standard numerical representation such as an array of floats. If all functions like
`table, mode, pdf, etc. ` were listed in this proposed input output section of the docs, it would make it much easier to get started for an hardcore array person like me.

**Comment by tlienart** [comment]
Thanks for the input!

**Tables v Matrix**: this is by-design and should be seen in a broader context where we want to have the flexibility to consider columns (features) independently rather than  just raw data->single model->output. (In other words there are good reason why we try to enforce Tables; particularly the notion of ScientificTypes per column). That being said I agree that it should be made clear what to  do  if you just have an array and just want to  feed it to a model a la sklearn. In that case, as it seems you found out, using `MLJBase.table(matrix)` will do the  trick. 

_Action point_:

- re-export `table` from `MLJBase` so that it's directly accessible in MLJ (#380)
- add explicit example for how to do this

**pdf, mode, ...**: it seems that here the main pain point is missing examples/docs

- add example/tutorial for how to do work with `UnivariateFinite` objects

xref: matrix v table discussion #50

**Comment by ablaom** [comment]
#648 puts finishing touches on this
