### ISSUE TITLE
Documentation of extracting best fitted params

### ISSUE THREAD

**Issue by baggepinnen** [alan-turing-institute/MLJ.jl#386]
I can't figure out how to get the best fitted parameters of a self tuning model. The docs say

> Once a tuning machine mach has bee trained as above, one can access the learned parameters of the best model, using fitted_params(mach).best_fitted_params.

If I try to do that, I get a named tuple I have no idea how to use
```julia
julia> p = fitted_params(mac).best_fitted_params
(fitresult = WrappedEnsemble @ 1…58,)
```
I can not train the tuple, the fitresult in the tuple, and I can not seem to find anything I can train down there. If I plow through the type I find
```
p.fitresult.atom
```
which actually prints the values of the parameters. All intermediate objects just print a cryptic string in stdout
```
julia> p = fitted_params(mac).best_fitted_params
(fitresult = WrappedEnsemble @ 1…58,)

julia> p.fitresult
WrappedEnsemble @ 1…58
```

## Action points
- Describe how to make use of the fitresult. Ideally, I would like to know how to get a model I can put in a machine and train, or at least see the best parameters somehow, maybe in a named tuple.
- Consider improving printing of types, `WrappedEnsemble @ 1…58` is very cryptic.

**Comment by ablaom** [comment]
@baggepinnen Thanks for sharing your experience. I can see that the documentation is lacking. 

To help improve the docs, let me try to first solve your problem. 

> Ideally, I would like to know how to get a model I can put in a machine and train,

So, the best model is obtained with `fitted_params.best_model`, not `fitted_params.best_fitted_params`. So you could do

```julia
best = fitted_params.best_model
mach2 = fit!(machine(best, X, y))
ynew = predict(mach2, Xnew)
```

However, this is actually unnecessary, because when you fit! the `TunedModel` machine, `mach`, this has already been done for you internally, as a last step (after optimising, and as explained in the `TunedModel` doc string).  So the above is equivalent to

```julia
ynew = predict(mach, Xnew)
```

This is what is meant when we say a `TunedModel` is like a "self-tuning" version of the original wrapped `model`. 

> or at least see the best parameters somehow,

I assume you mean best *hyperparameters* here. Then `fitted_params(mach).best_model` ought to do this. To get it as a named tuple, you can apply `params` to the result. 

Do these comments help you achieve your goal?

> Consider improving printing of types, WrappedEnsemble @ 1…58 is very cryptic.

Well, I assume you don't want to see all 100 fit results, but I agree this could be improved. Just FYI, if you type `@more` at the REPL after any MLJ object, it will give you a dump of that object.

**Comment by ablaom** [comment]
Closing for lack of a response to request for further information. Feel free to re-open. 

For the record this issue (now resolved) may have some bearing on the matter: https://github.com/alan-turing-institute/MLJBase.jl/issues/254

Finally, the two methods `fitted_params` and `report` now have detailed doc-strings with examples.
