### ISSUE TITLE
LogisticClassifier inconsistent interface across scikitLearn and MLJLinearModels

### ISSUE THREAD

**Issue by dsweber2** [alan-turing-institute/MLJ.jl#387]
**Describe the bug**
All of the parameters in the case of scikitLearn need to be strings, rather than symbols, while the opposite is true for MLJLinearModels. This makes switching between the two awkward. This could potentially be considered a feature request, depending on intended behavior.

**To Reproduce**
compare
```julia
using MLJ
@load LogisticClassifier pkg="MLJLinearModels"
model = LogisticClassifier(penalty="l1", multi_class="false")
```
vs 
```julia
using MLJ
@load LogisticClassifier pkg="ScikitLearn"
model = LogisticClassifier(penalty=:l1, multi_class=false)
```

**Expected behavior**
both should produce the same classifier with different backends.

**Additional context**

**Versions**
I'm on the master branch
<details>

</details>

**Comment by tlienart** [comment]
> **Expected behavior**
> both should produce the same classifier with different backends.

So I agree that some similarity in how things are called  make things easier, these are two different packages and should be considered as such. MLJLinearModels is **not meant** to be a copy of what sklearn does, for instance the penalty parameter "lambda" is not the same as sklearn's "alpha". While I appreciate that this may lead to confusion for people who want to use both for comparisons, I made deliberate design decisions not to copy sklearn in all things primarily because it simplifies generalization a lot allowing MLJLM to already support many more models than sklearn (though of course the whole lot is not as mature, MLJLM is still very much experimental).

Back to the original point, I think for the penalty specification your comment is fair and MLJLM 0.2.4 (pending release) supports passing string identifiers for penalties so that you can write

```julia
MultinomialClassifier(penalty="l1")
```

Thanks for reporting, I'll close this issue but feel free to re-open if you disagree / have other comments.
