### ISSUE TITLE
Errors in MLJ (probably data format)

### ISSUE THREAD

**Issue by azev77** [alan-turing-institute/MLJ.jl#405]
```julia
#There are some data format issues. 
#For example the following works giving 48 matching models
d = dataset("MASS", "Boston");
d = coerce(d, autotype(d, :discrete_to_continuous));
y, X = d.MedV, select(d, Not(:MedV));
train, test = partition(eachindex(y), 0.70, shuffle=true, rng=52)
mm=models(matching(X, y))
@load ARDRegressor pkg= ScikitLearn;
score, scoren = [],[];
reg = ARDRegressor();
m = machine(reg, X, y);
fit!(m, rows=train);
ŷ = predict(m, rows=test);

#However, the following only gives 2 matching models & fit! does not work
d = dataset("ISLR", "Auto");
d = coerce(d, autotype(d, :discrete_to_continuous));
y, X = d.Weight, select(d, Not(:Weight));
train, test = partition(eachindex(y), 0.70, shuffle=true, rng=52);
mm=models(matching(X, y))
@load ARDRegressor pkg= ScikitLearn;
score, scoren = [],[];
reg = ARDRegressor();
m = machine(reg, X, y);
fit!(m, rows=train);
ŷ = predict(m, rows=test);

#Even the following only gives 2 matching models & fit! does not work 
X, y = @load_reduced_ames
X = DataFrame(X)
train, test = partition(eachindex(y), 0.70, shuffle=true, rng=52);
mm=models(matching(X, y))
@load ARDRegressor pkg= ScikitLearn;
score, scoren = [],[];
reg = ARDRegressor();
m = machine(reg, X, y);
fit!(m, rows=train);
ŷ = predict(m, rows=test);
```

</details>

**Comment by tlienart** [comment]
You may find the function `schema` quite useful. For instance in the first case:

```julia
julia> schema(d)
_.table = 
┌──────────────┬─────────┬────────────┐
│ _.names      │ _.types │ _.scitypes │
├──────────────┼─────────┼────────────┤
│ MPG          │ Float64 │ Continuous │
│ Cylinders    │ Float64 │ Continuous │
│ Displacement │ Float64 │ Continuous │
│ Horsepower   │ Float64 │ Continuous │
│ Weight       │ Float64 │ Continuous │
│ Acceleration │ Float64 │ Continuous │
│ Year         │ Float64 │ Continuous │
│ Origin       │ Float64 │ Continuous │
│ Name         │ String  │ Unknown    │
└──────────────┴─────────┴────────────┘
_.nrows = 392
```

So you can see that there is one column that is not recognised. You could force `Name` to `categorical` but it wouldn't make much sense, let's just drop that column and see:

```julia
julia> select!(X, Not(:Name));
julia> mm=models(matching(X, y))
48-element Array{NamedTuple,1}:
 (name = ARDRegressor, package_name = ScikitLearn, ... )
 (name = AdaBoostRegressor, package_name = ScikitLearn, ... )
 (name = BaggingRegressor, package_name = ScikitLearn, ... )
 (name = BayesianRidgeRegressor, package_name = ScikitLearn, ... )
 (name = ConstantRegressor, package_name = MLJModels, ... )
 (name = DecisionTreeRegressor, package_name = DecisionTree, ... )
 (name = DeterministicConstantRegressor, package_name = MLJModels, ... )
 (name = DummyRegressor, package_name = ScikitLearn, ... )
 (name = ElasticNetCVRegressor, package_name = ScikitLearn, ... )
 (name = ElasticNetRegressor, package_name = MLJLinearModels, ... )
 ⋮
 (name = RidgeRegressor, package_name = MultivariateStats, ... )
 (name = RidgeRegressor, package_name = ScikitLearn, ... )
 (name = RobustRegressor, package_name = MLJLinearModels, ... )
 (name = SGDRegressor, package_name = ScikitLearn, ... )
 (name = SVMLRegressor, package_name = ScikitLearn, ... )
 (name = SVMNuRegressor, package_name = ScikitLearn, ... )
 (name = SVMRegressor, package_name = ScikitLearn, ... )
 (name = TheilSenRegressor, package_name = ScikitLearn, ... )
 (name = XGBoostRegressor, package_name = XGBoost, ... )
```

### Thoughts

There may be value in telling the user that one of the feature is considered of `Unknown` type  when  calling `models(matching...` what do you think would have helped you here?

**Comment by azev77** [comment]
Thank you  @tlienart for addressing this. 
1 it would have helped if models(matching(X,y)) told me why 
2 it would have also helped if the error given by fit!(m) also told me it is a data format issue 

3 Could you please show how to automatically convert data to a form that works w/ models(matching()) and fit!() for the AMES data (probably some kind of coerce() statement): 

X, y = @load_ames;
train, test = partition(eachindex(y), 0.70, shuffle=true, rng=52);
mm=models(matching(X, y))
@load ARDRegressor pkg= ScikitLearn;
reg = ARDRegressor();
m = machine(reg, X, y);
fit!(m, rows=train);
ŷ = predict(m, rows=test);

4 I updated MLJLinear models, Huber/LAD/Quantile/Robust still not working.

**Comment by tlienart** [comment]
Thanks for reporting this, for (4) see the original issue which I re-opened, the issue is  fixed as far as I can tell but if not then there's something else we need to figure out.

For 1,2, yes I think this is reasonable.

For 3, did you look at [this tutorial](https://alan-turing-institute.github.io/MLJTutorials/pub/end-to-end/AMES.html) ?

More generally, the question is a little bit ambiguous but your input is welcome. Would you ideally like to have 

- something that drops columns in such a way  that the resulting data is  appropriate for model X
- something that just drops Unknown columns?
- something that tells you which columns are currently  problematic for model X and that you could try coercing in some specific way? 

(I'm brainstorming here, it's hard to come up with  general rules, of course more help for the user is always great so displaying better messages as per (1,2) seems a sensible first step, but there's a question of how much we could potentially do for the user automatically  and whether that would be a  good idea or not)

**Comment by azev77** [comment]
I found a clunky & slow way to do it, but it works for now. 

```
X, y =  @load_ames; train, test = partition(eachindex(y), .7, rng=333);

sch = schema(X);
println(rpad(" Name", 15), rpad(" Type", 30), rpad(" Scitype", 20))
println("-"^75)
for (name, ty, scitype) in zip(sch.names, sch.types, sch.scitypes)
    println(rpad("$name", 15), rpad("$ty", 30), scitype)
end
for (name, scitype) in zip(sch.names, sch.scitypes)
    if scitype ≠ Continuous
        global X = coerce(X, :($name) =>Continuous);
    end
end
sch = schema(X);
println(rpad(" Name", 15), rpad(" Type", 30), rpad(" Scitype", 20))
println("-"^75)
for (name, ty, scitype) in zip(sch.names, sch.types, sch.scitypes)
    println(rpad("$name", 15), rpad("$ty", 30), scitype)
end

matching_models = models(matching(X, y))
model_names = load_everything(matching_models)
dropm = ("ConstantRegressor", "HuberRegressor","LADRegressor","LassoCVRegressor","QuantileRegressor","RobustRegressor");
filter!(m -> m ∉ dropm , model_names)
@time all_scores = [score_model(m, X, y, train, test) for m in model_names]
model_names[ argmin(all_scores) ] , argmin(all_scores), minimum(all_scores)
model_names[ sortperm(all_scores) ]


```

**Comment by tlienart** [comment]
Well if it works for you, great, but bear in mind that this ScientificTypes business is not just there to burden people, it's there to  avoid doing non-sensical stuff. The way you're doing it is the worst  possible way because you don't check what you're doing with the data. Ultimately  what you're doing **only** makes sense for  the  `Count=>Continuous` conversion, and you can achieve that in a safer manner by using the  `discrete_to_continuous` rule:

```julia
data2 =  coerce(data, autotype(data, :discrete_to_continuous))
```

But, for instance, if you had  columns with Strings, then this conversion to  Continuous would  make no sense.  So first you'd have to drop those columns (or re-encode them) then apply some rule. 

I'm saying this in case you want to  add this in a blog post as you stated on Discourse;  if it's just for your experimentation then  of course, do whatever  works 😄
