### ISSUE TITLE
Stackoverflow if calling MLJBase.int on a non-categorical

### ISSUE THREAD

**Issue by tlienart** [alan-turing-institute/MLJ.jl#407]
### Reproducing example

I made a simple error of using a classifier instead of a regressor but the error was too harsh

```julia
using DataFrames, MLJ
rawdata = DataFrame(make=["honda", "ford", "subaru"], mpg=[33,29,31], price=[30000,25000,27500]);

@load DecisionTreeClassifier;

pp = @pipeline OneHotDT(
    X -> coerce(X, :make=>Multiclass),
    hot = OneHotEncoder(),
    dtc = DecisionTreeClassifier()) is_probabilistic=true;

dtm = machine(pp, select(rawdata, Not(:price)), select(rawdata, :price)) 
fit!(dtm)
```

Staktrace

```
[ Info: Training Machine{OneHotDT} @ 1…93.
[ Info: Training NodalMachine{OneHotEncoder} @ 5…85.
[ Info: Spawning 3 sub-features to one-hot encode feature :make.
[ Info: Training NodalMachine{DecisionTreeClassifier} @ 1…08.
ERROR: StackOverflowError:
Stacktrace:
 [1] int(::DataFrame) at /Users/tlienart/.julia/dev/MLJBase/src/data.jl:342
 [2] #int#37(::Nothing, ::typeof(MLJBase.int), ::DataFrame) at /Users/tlienart/.julia/dev/MLJBase/src/data.jl:342
 ... (the last 2 lines are repeated 39997 more times)
 [79997] int(::DataFrame) at /Users/tlienart/.julia/dev/MLJBase/src/data.jl:342
```

### Why & Fix

`MLJBase.int` fails on a non-categorical array. It shouldn't or at least it should fail early  with a warning message that probably we did something wrong

**Comment by ablaom** [comment]
I think the real issue here is that while constructing a machine forces certain type checks, these checks depend on the model having appropriately defined `input_scitype` and `target_scitype` traits overloaded. At the moment, *composite* models, defined by exporting a learning network or using @pipeline, do not have these traits defined (ie they fallback to `Unknown` values, which the type checker is designed to ignore). Knowing what these traits should actually be is a bit problematic, because a pipeline (for example) might have a leading transformation that changes the scientific type of the data. If this transformation is just a *function* (which is allowed) then we have no obvious way of deducing the appropriate `input_scitype` declaration. 

For an arbitrary composite (defined by exporting a learning network) I think the solution is to allow the user to declare the relevant scitypes as part of the export syntax; see also #381 .

For a pipeline, I propose we add trait definitions for the common use cases where we actually do know how to set the traits; see #412

I will add the suggested informative error message to `MLJBase.int`

**Comment by ablaom** [comment]
resolved by PR above
