### ISSUE TITLE
"A simple deterministic regressor" doc is outdated

### ISSUE THREAD

**Issue by cstjean** [alan-turing-institute/MLJ.jl#421]
Running the code in https://alan-turing-institute.github.io/MLJ.jl/stable/simple_user_defined_models/#A-simple-deterministic-regressor-1, in particular the part below, yields an error.

```julia
julia> using MLJ
julia> task = load_boston()
julia> model = MyRegressor(lambda=1.0)
julia> regressor = machine(model, task)
ERROR: Use `machine(model, X, y)` or `machine(model, X, y, w)` for a supervised model. 
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] machine(::MyRegressor, ::NamedTuple{(:Crim, :Zn, :Indus, :Chas, :NOx, :Rm, :Age, :Dis, :Rad, :Tax, :PTRatio, :Black, :LStat, :MedV),Tuple{Array{Float64,1},Array{Float64,1},Array{Float64,1},Array{Int64,1},Array{Float64,1},Array{Float64,1},Array{Float64,1},Array{Float64,1},Array{Float64,1},Array{Float64,1},Array{Float64,1},Array{Float64,1},Array{Float64,1},Array{Float64,1}}}) at /Users/cedric/.julia/packages/MLJBase/t7MaX/src/machines.jl:47
 [3] top-level scope at REPL[15]:1
```
I'd fix it, except that I can't figure out which elements of `load_boston()` are features and which element is target.

**Comment by OkonSamuel** [comment]
The docs need to be updated. The error occurred because from [MLJBase](https://github.com/alan-turing-institute/MLJBase.jl) 0.5, the`load_boston()` function no longer returns a `SupervisedTask` as it used to, it now returns a `NamedTuple` instead.

The example in the documentation makes use of `:MedV` column as the target while the feature matrix `X` consists of all other columns except `:Chas` is the feature matrix `X`. see [previous code](https://github.com/alan-turing-institute/MLJBase.jl/blob/v0.4.0/src/datasets.jl#L10-L17)

**Comment by ablaom** [comment]
Thanks for that OkonSamuel .

To clarify further, the data load *functions* load a single table with target and features combined. This happens to be "column table" `t` (named tuple of vectors of equal length) because we dumped DataFrames/CSV as dependencies. You can convert is to a DataFrame with `DataFrame(t)` if you want (or any other Tables.jl compatible table in a similar way).

The data load *macros* return a *pair* of objects `X` (a column table of features) and `y` (a target vector).
