### ISSUE TITLE
CI is not generating documentation

### ISSUE THREAD

**Issue by ablaom** [alan-turing-institute/MLJ.jl#432]
The documentation is no longer in sync. In latest PR to master, I noticed that no documentation generation was appearing in the travis jobs. 

Related to https://github.com/JuliaDocs/Documenter.jl/issues/1228 ?

**Comment by tlienart** [comment]
this should be fixed.

Note that I had to remove `nightly` from the test matrix, this is because the `allow_failure` doesn't work anymore as far as I can  tell. 

Long story short `matrix` and `jobs` are overwriting keywords, we have to put  everything in  `matrix` now but for some unknow reason if  you do that, then travis will ignore allow failure. Anyway...

**Comment by tlienart** [comment]
PS: it fails atm due to compat crap but that  will be fixed once I update MLJ to work with MLJBase's latest release
