### ISSUE TITLE
AMES tutorial doesn't work (UndefVarError) if ScikitLearn.jl or StatsBase.jl are loaded

### ISSUE THREAD

**Issue by uhtewihptihwue** [alan-turing-institute/MLJ.jl#534]
The AMES example (first end-to-end example in the docs; https://alan-turing-institute.github.io/MLJTutorials/end-to-end/AMES/) doesn't work out-of-the-box if the user has ScikitLearn.jl loaded (this breaks the `fit!()` and `predict()` statements) or StatsBase.jl loaded (this breaks the `predict()` statement). Because those are very common packages, could those statements be changed to `MLJ.fit!()` and `MLJ.predict()` to reduce friction? I think it would be valuable to have the basic examples working with as little need to troubleshoot as possible.

An error is `UndefVarError: fit! not defined` and a warning is `WARNING: both ScikitLearn and MLJ export "fit!"; uses of it in module Main must be qualified`.

**Comment by ablaom** [comment]
Thanks for that feedback. Much appreciated. 

For testing out-of-the-box we always recommend a fresh environment (see  https://github.com/alan-turing-institute/MLJ.jl#using-mlj) or, in the case of the tutorials, the explicitly provided environment (see the very first instructions on the tutorial site: https://alan-turing-institute.github.io/MLJTutorials/).

I guess my first question, as this has never come up before, is why you want to use ScikitLearn simultaneously with MLJ? MLJ wraps a bunch of ScikitLearn models already. What other tools from there are you wanting to use, that need `fit!` and `predict`? And what are you using from `StatsBase`?

Originally, we did extend the `fit` and `predict` methods from StatsBase, but this was abandoned because we wanted a completely dependency-free base-level model API (MLJModelInterface), so that 3rd party packages could implement the MLJ interface without adding any deps. I expect that it is unlikely MLJ would revert this decision. Can you think of a work-around that would not force MLJ users to do `MLJ.fit!` and `MLJ.predict`?

In my opinion it's fine that all these packages export their methods. You can always pick a favourite, do `using` for that package and `import` for the rest. 

Or perhaps I misunderstand your issue?

**Comment by uhtewihptihwue** [comment]
Thanks very much for responding. You correctly understand my issue. You're right that this could've been avoided if I simply had read the MLJ home page in addition to the MLJ XGBoost example.

Before trying to run this example, I'd been trying code samples from some tutorials that used ScikitLearn.jl and StatsBase.jl. That's why they were loaded in my environment.

Thanks for your work on this library and its excellent tutorial.
