### ISSUE TITLE
Accessing nested machines is (still) awkward

### ISSUE THREAD

**Issue by tlienart** [alan-turing-institute/MLJ.jl#553]
I'm not sure how this should be done but in the tutorials at the moment I'm using at one point:

```julia
assignments = first(values(report(spca2).report_given_machine)).assignments
```

for a Standardizer + PCA. 

This is... not ideal, but is probably not the right way to do it either.

Additionally  it turns out this new `report_given_machine` is a Dictionary so it can't be accessed by index, it can only be accessed by name but the names are not strings, they're these weird type objects. I imagine there must be a principled way to access these things?

**Comment by cscherrer** [comment]
Similar for getting parameter estimates of components, I end up doing things like

```julia
p = fitted_params(m);
p.fitted_params_given_machine[p.machines[1]]
p.fitted_params_given_machine[p.machines[2]][:mean_and_std_given_feature]
```

I don't know what's the right way to do it, but my approach here is pretty awful.

**Comment by tlienart** [comment]
Hmm your approach to pass objects as key  must be right. Maybe this could be fixed in many cases by just allowing machines in the pipeline to have an ID and then you could do

```
p.fitted_params_given_machine[:std]
p.fitted_params_given_machine[:lm]
```

I think @ablaom has thought about all this quite a bit though so let's just see what he says

**Comment by cscherrer** [comment]
Thanks @tlienart . I had mentioned this on Slack, and IIRC @ablaom said this doesn't quite work because you could have the same model multiple times in one machine. But maybe the IDs could be distinct? We also might have just been talking past each other.

**Comment by ablaom** [comment]
Yeah, this is the recommended way of doing this currently:

```julia
p = fitted_params(m);
p.fitted_params_given_machine[p.machines[1]]
p.fitted_params_given_machine[p.machines[2]][:mean_and_std_given_feature]
```

The order of the machine is always the same. And I have reversed it in this PR: https://github.com/alan-turing-institute/MLJBase.jl/pull/310 . That said, as pointed out, the fact that we key our dictionary on objects created under the hood is  less than ideal. 

Pipelines are a special case of a more general construct - an exported learning network - in which case the complications you are experiencing make perfect sense (at least to me 😄 ) but it all looks like an unnecessary contrivance in the pipeline case. I get that. 

For the record, here's the crux of the matter in the general case: When a user constructs a composite model, he is creating a new struct with models as hyperparameters. When he fits an instance, various machines get created, under the hood. (Just think of a machine as a placeholder for some learned parameters). These machines are *not* generally in one-to-one correspondence with the models specified. In principle, several machines could share the same model, as in a homogeneous ensemble. For example, you train 10 decision trees, leading to 10 sets of learned parameters, but all these trees share a common set of hyperparameters (model) - the standard implementation of a random forest. If I do `fitted_pamams[:tree]` which tree's learned parameters do you want? It's ambiguous. 

Now I daresay no-one will ever want to construct a pipeline where the hyperparameters of distinct components in the pipelines are coupled. So we could hack a different API for this case. But then advanced users who want to build more sophisticated composites will have to unlearn the wrong idea that models (hyper-parameters) and learned parameters are always fused. This is my concern. 

That said, there has been enough complaint regarding this issue that my concerns are probably not as important as the frustration being experienced in the status quo. What if, as has been more-or-less suggested,  `fitted_params(my_composite)` returns a named tuple whose keys are the component model (field) names and whose value in each case is the corresponding `fitted_params(mach)` when `mach` is the unique machine created using that model, and a *vector* of `fitted_params` otherwise (probably never, in the case of pipelines)?

So, I can do something like

```julia
fitted_params(my_pipe).linear_rgs.coeffs 
```

and get one set of coefficients, but for an homogeneous ensemble-like mode I do:

```julia
atomic_params = fitted_params(my_funky_ensemble).linear_rgs   # a vector
atomic_params[31].coeffs
```

**Comment by tlienart** [comment]
> These machines are _not_ generally in one-to-one correspondence with the models specified. In principle, several machines could share the same model, as in a homogeneous ensemble.

Then why not have a mechanism to give _machines_ an id, is  there something that prevents it? the id would be like a learned parameter but fixed? if multiple are generated as a homogenous ensemble you could just have the convention that you'd get an  array?

**Comment by CameronBieganek** [comment]
I'm pretty new to MLJ and I haven't had the chance to try out learning networks. So I don't have a strong sense for the design issues here, but my general feeling is this:

> Easy things should be easy, and hard things should be possible.

I would guess that ~90% of potential MLJ users will only use linear pipelines. Linear pipelines are the easy thing that should have an easy interface. Learning networks are the hard thing that should be possible. Since only ~10% of users will use learning networks, the simplicity of the pipeline interface should be more important than making learning networks easy.

**Comment by ablaom** [comment]
@CameronBieganek Maybe even less than 10% 😄 

@tlienart 

> Then why not have a mechanism to give machines an id, is there something that prevents it? the id would be like a learned parameter but fixed? if multiple are generated as a homogenous ensemble you could just have the convention that you'd get an array? this is maybe a dumb idea, just trying to understand the constraints.

Could you flush out your idea a little more? Isn't the index of a machine in `fitted_params(my_compoisite).machines` the same thing, essentially?

**Comment by tlienart** [comment]
my perspective on the thing may be hazy, it might be better to work with two typical examples that you could provide and we could discuss what a  good  compromise  API could be? 

The thing I was thinking about is something like:

```
p = pipeline(op1=Model1(), op2=Model2(), ...)
m = machine(p, X, y)
fit!(m, rows=train)
report(m)[:op1] # <-- get the report of the machine at op1
fitted_params(m)[:op1]  # <-- get the fitted params at op1
```

Under the hood the machine that works around `Model1()` could have an extra field "name" or something and keep  track  of the fact that it's called `op1` in the pipeline. 

I've not looked extensively at the pipeline code / learning network so my  thoughts on this may  just  not work or not take into consideration  some intrinsic difficulties. But I think an API like the above would be easier to remember.

**Comment by ablaom** [comment]
I think this is more-or-less what I was suggesting above - just using named tuples instead of dictionaries. So: 

```julia
p = pipeline(op1=Model1(), op2=Model2(), ...)
m = machine(p, X, y)
fit!(m, rows=train)
report(m).op1 # <-- get the report of the machine at op1
fitted_params(m).op1  # <-- get the fitted params at op1
```

If `op1` is itself a pipeline with models `ap1` and `ap2` then

```julia
report(m).op1.ap2 # get a nested report
```

**Comment by tlienart** [comment]
@gd1989 you’ll want to have a look at this and possibly discuss on Monday, we’ll need to review existing tutorials to make sure they use the right syntax & ideally write a super simple one that presents just the syntax

**Comment by gd1989** [comment]
thanks for the heads up @tlienart. Will have a look
