### ISSUE TITLE
Something not right with the Binder project file?

### ISSUE THREAD

**Issue by ablaom** [alan-turing-institute/MLJ.jl#587]
If I follow the binder link from the docs, it loads fine until I get to `using PyPlot`, in which case the environment complains that `PyPlot` is not in the project:

![Screen Shot 2020-07-07 at 1 18 54 PM](https://user-images.githubusercontent.com/30517088/86682703-f0ebea00-c054-11ea-8578-dffc19d7e384.png)

On investigating further, it seems the active env is different from that in binder/Project.toml:

![Screen Shot 2020-07-07 at 1 21 46 PM](https://user-images.githubusercontent.com/30517088/86682798-095c0480-c055-11ea-980d-251d10610309.png)

@darenasc Any chance you can take a look at this?

**Comment by darenasc** [comment]
yes, I'll look into that.

**Comment by darenasc** [comment]
It seems that the `Project.toml` takes precedence over the `binder/Project.toml` file, that's why is not installing the other packages used in the notebook. A solution would be to install the packages from the notebook with `Pkg`, here is the [notebook](https://mybinder.org/v2/gh/darenasc/MLJ.jl/dev?filepath=binder%2FMLJ_demo.ipynb).

**Comment by ablaom** [comment]
> A solution would be to install the packages from the notebook with Pkg

Not sure I follow. I assume you don't mean add new dependencies to MLJ? Do you mean start the notebook with something like:

```julia
Pkg.activate(@__DIR__)
Pkg.instantiate()
```

If that works, that sounds like a good solution to me.
