### ISSUE TITLE
No classifier matches when X has categorical columns except ConstantClassifier

### ISSUE THREAD

**Issue by abnud1** [alan-turing-institute/MLJ.jl#687]
I'm trying to solve the titanic competition problem from the Kaggle website, here is the link to the competition: https://www.kaggle.com/c/titanic

the data has categorical columns not only in the target(which is Survived) but also in other columns like Pclass for example.

in short, X has categorical columns and it seems that only `ConstantClassifier` and its deterministic brother can deal with categorical data in X.

**Versions**
julia: 1.5.2
MLJ: 0.14.1
OS: Archlinux

**Comment by ablaom** [comment]
This is because all the other classifiers generally require `Continuous` inputs. You need to first transform the data using `ContinuousEncoder`. However, you should probably check your data is being correctly interpreted first by looking at the scitype column after applying `schema` to your data. You may need to `coerce` some of the types. When you have the hang of this, you may want to combine your chosen classifier with the transformer in a `@pipeline`. There are examples of these workflows at https://github.com/ablaom/MachineLearningInJulia2020 and https://alan-turing-institute.github.io/DataScienceTutorials.jl/ .
