### ISSUE TITLE
GSoC Project Proposal

### ISSUE THREAD

**Issue by ysimillides** [alan-turing-institute/MLJ.jl#78]
For adding to https://julialang.org/soc/ideas-page
We are looking for 1-2 students to join us over the summer in the MLJ.jl toolbox (Machine-Learning in Julia). You can find us on the MLJ channel on the Julia slack to discuss the project. Ideally we would like the project to combine a few of the following ideas, although we look forward to hearing your own suggestions : 

1. Implement interfaces to popular data science algorithms, written in both Julia and non-Julia, such as parts of ScikitLearn or Flux.
2. Write worked examples/tutorials of using the MLJ codebase to solve a variety of problems, relevant to our userbase, serving as a first introduction to using the library.
3. Write pure Julia code for some of the MLJ algorithms to replace non-Julia elements of the library.

**Comment by aviks** [comment]
Do a PR for https://github.com/JuliaLang/www.julialang.org/blob/master/soc/ideas-page.md ?

**Comment by ablaom** [comment]
I'm not sure I'm going to have time to remotely supervise a summer student unless I'm very sure about their abilities. I already expect to be helping @ayush1999 out. 

I feel your own time might be more effectively devoted to developing, rather than supervising. If the student had a very strong Statistics background this might work out, as you could help them with the Julia, but a summer student is always a bit of a crap-shoot in terms of productivity. They can be a good investment for later on, but they often require more time than you think. I suppose it is ultimately @sjvollmer 's call as to whether you want to take this on.
