### ISSUE TITLE
Show is too long for MulticlassPrecision and MulticlassTruePositiveRate

### ISSUE THREAD

**Issue by KronosTheLate** [alan-turing-institute/MLJ.jl#923]
The current way of `show`ing `MulticlassPrecision()` and `MulticlassTruePositiveRate()` are both so long that the output table from `evaluate` is too long to fit in my terminal:
<img width="960" alt="image" src="https://user-images.githubusercontent.com/61620837/161916811-85210cd8-b9d8-4ec6-8e36-0a2b951a6d0b.png">

Could this output get a prettier/shorter format? This would ofc apply to all metrics that are long when `show`n.

**Comment by ablaom** [comment]
Yeah, this is tricky to get right in a generic way because some metrics really need the type parameters shown to be unambiguous. For example, in a regression problem you  might use both `LPDistLoss(1)` and `LPDistLoss(2)`. 

As this is polish, it might take a while to around to get fixed. PR welcome. Relevant code is [here](https://github.com/JuliaAI/MLJBase.jl/blob/95efa58e9e7a9c8818ebeb917323e744c8606ae8/src/measures/measures.jl#L151).

**Comment by KronosTheLate** [comment]
Sounds great. Do you agree with the approach of ad-hoc shortening the shown value in the table? That is, make the value shown in the table potentially different from the value shown when returning the metric?

**Comment by ablaom** [comment]
Okay, I did have a look at this as `MLJBase/src/show.jl` is not the prettiest bit of code. Please see https://github.com/JuliaAI/MLJBase.jl/pull/757 for a proposal.
