### ISSUE TITLE
Question about using `acceleration` to implement parallelism

### ISSUE THREAD

**Issue by bearberror** [alan-turing-institute/MLJ.jl#934]
I have encountered an error when fit the model by using  fit(machine, X, y, acceleration = CPUThreads()) 
CPU1() is an only the option

From my little knowledge, It is possible to fit! with CPUThreads() option or Is it possible to accelerated to fitted the model with this option ??

**Comment by ablaom** [comment]
@bearberror Thanks for reporting. 

Acceleration in MLJ is controlled by hyper-parameters of the model (fields of the model struct), not by specifying keyword arguments to `fit!`. This is because not all models support parallelism. This parameter is usually called `acceleration` but many 3rd party models use a different name, such as `device`.  Here's an example:

Here's an example:
```julia
using MLJ,  ComputationalResources
julia> model = NeuralNetworkClassifier(acceleration=CUDALibs())
NeuralNetworkClassifier(
    builder = Short(
            n_hidden = 0,
            dropout = 0.5,
            σ = NNlib.σ),
    finaliser = NNlib.softmax,
    optimiser = Flux.Optimise.ADAM(0.001, (0.9, 0.999), 1.0e-8, IdDict{Any, Any}()),
    loss = Flux.Losses.crossentropy,
    epochs = 10,
    batch_size = 1,
    lambda = 0.0,
    alpha = 0.0,
    rng = Random._GLOBAL_RNG(),
    optimiser_changes_trigger_retraining = false,
    acceleration = ComputationalResources.CUDALibs{Nothing}(nothing))
```
Not a lot of models support parallelism but those that do include ones provided by these packages: ParallelKMeans, Flux, XGBoost, LightGBM. 

Often in machine learning there is an opportunity to use parallelism at a higher level, for example in cross-validation. The `evaluate/evaluate!` method *does* provide `acceleration` as a keyword argument and `CPUThreads()` and `CPUProcesses()` are both options. Other examples are model optimisation (tuning) and bagging. The first is provided by the MLJ model wrapper `TunedModel(model=...)` and the second by `EnsembleModel(model=...)`. These "metamodels" have `acceleration` as a hyperparameter.  You can find examples of specifying `acceleration` in `evaluate` and `TunedModel`  in [this tutorial](https://github.com/alan-turing-institute/MLJ.jl/blob/dev/examples/telco/notebook.ipynb).
