### ISSUE TITLE
Factor out performance evaluation tools

### ISSUE THREAD

**Issue by KronosTheLate** [alan-turing-institute/MLJ.jl#947]
In looking for how to make a confusion matrix in julia, googling lead me to [EvalMetrics.jl](https://github.com/VaclavMacha/EvalMetrics.jl). They do however not support e.g. multiclass confusion matrices, which MLJ handles great. I have [asked to link to MLJ.jl](https://github.com/VaclavMacha/EvalMetrics.jl/issues/8) in their documentation to make it easier to find, but this would only be a band-aid fix.

The evaluations tools found in MLJ seem very good, and have great general applicability to any and all machine learning, e.g. Flux. Therefore, I suggest moving the core functionality used to evaluate performance into a separate package, akin to EvalMetrics.jl, just in a more feature-complete and solid version.

**Comment by ablaom** [comment]
Thanks for the positive feedback and suggestion. I think there are some limitations for using our classification metrics directly in Flux, because a raw probability vector delivered by Flux has to be converted to [`UnivariateFinite` object](https://github.com/JuliaAI/CategoricalDistributions.jl) (or array thereof) and I possibly Zygote doesn't like the dictionary implementation there (last time I checked).   But yeah, it would be useful to factor this out, and this is on the list: 

Yes, moving this out is on the list: https://github.com/JuliaAI/MLJBase.jl/issues/416

Closing as tracked. 


Yes, moving measure out is on our list
