### ISSUE TITLE
WARNING: both MLJBase and DataFrames export "transform"; uses of it in module Main must be qualified

### ISSUE THREAD

**Issue by MrBenzWorld** [alan-turing-institute/MLJ.jl#991]
WARNING: both MLJBase and DataFrames export "transform"; uses of it in module Main must be qualified

**Comment by ablaom** [comment]
Sounds to me like you have the full DataFrames and MLJBase [namespaces](https://docs.julialang.org/en/v1/manual/modules/#namespace-management) in scope. Either use `import DataFrames` instead of `using DataFrames` or qualify the use of transform - that is, replace a plain `transform` with `DataFrames.transform` or `MLJBase.transform` depending on which `transform` you mean.

For example, I'm guessing you are working on [this example](https://alan-turing-institute.github.io/MLJ.jl/dev/learning_networks/#Example-D-Multiple-nodes-pointing-to-the-same-machine) but have all `DataFrames` names in scope. In that case try


```julia
function MLJBase.prefit(composite::CompositeD, verbosity, X, y)

    Xs = source(X)
    ys = source(y)

    mach1 = machine(:preprocessor, Xs)
    W = MLJBase.transform(mach1, Xs)  # <---------  see change here

    mach2 = machine(:target_transformer, ys)
    z = MLJBase.transform(mach2, ys)         # <----------------- see change here

    mach3 =machine(:regressor, W, z)
    zhat = predict(mach3, W)

    yhat = inverse_transform(mach2, zhat)

    # the learning network interface:
    return (
        predict = yhat,
        acceleration = composite.acceleration,
    )

end
```

**Comment by MrBenzWorld** [comment]
Thank you
